/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centro;

/**
 *
 * @author User
 */
public class newhistorias extends javax.swing.JFrame {

    /**
     * Creates new form newhistorias
     */
    public newhistorias() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        Anam = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtcon = new javax.swing.JTextArea();
        txtfirma = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdelito = new javax.swing.JTextArea();
        Situaciones = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        txtinforme = new javax.swing.JTextField();
        Motivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtconsulta = new javax.swing.JTextArea();
        Firma = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Detalle = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtdelitiva = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Motivo1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtconsulta1 = new javax.swing.JTextArea();
        Motivo2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtconsulta2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        Situaciones1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtdelitiva1 = new javax.swing.JTextArea();
        Situaciones2 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtdelitiva2 = new javax.swing.JTextArea();
        Situaciones3 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtdelitiva3 = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        Situaciones4 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtdelitiva4 = new javax.swing.JTextArea();
        Situaciones5 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtdelitiva5 = new javax.swing.JTextArea();
        Situaciones6 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtdelitiva6 = new javax.swing.JTextArea();
        Situaciones7 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtdelitiva7 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Anam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Anam.setText("Genograma ");

        txtcon.setColumns(20);
        txtcon.setRows(5);
        jScrollPane5.setViewportView(txtcon);

        txtdelito.setColumns(20);
        txtdelito.setRows(5);
        jScrollPane2.setViewportView(txtdelito);

        Situaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Situaciones.setText("Valoracion del soporte socio-familiares");

        con.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        con.setText("Diagnostico Inicial");

        Motivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Motivo.setText("Antecedentes personales");

        txtconsulta.setColumns(20);
        txtconsulta.setRows(5);
        jScrollPane1.setViewportView(txtconsulta);

        Firma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Firma.setText("Firma de responsabilidad");

        Fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fecha.setText("Fecha de elaboración informe");

        Detalle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Detalle.setText("Antecedentes familiares");

        txtdelitiva.setColumns(20);
        txtdelitiva.setRows(5);
        jScrollPane4.setViewportView(txtdelitiva);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("NOMBRES Y APELLIDOS");

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIA CLINICA");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 45, 65)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("GUARDAR");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("IMPRIMIR");

        Motivo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Motivo1.setText("Motivo de Consulta");

        txtconsulta1.setColumns(20);
        txtconsulta1.setRows(5);
        jScrollPane6.setViewportView(txtconsulta1);

        Motivo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Motivo2.setText("Factores desencanantes del episodio actual");

        txtconsulta2.setColumns(20);
        txtconsulta2.setRows(5);
        jScrollPane7.setViewportView(txtconsulta2);

        Situaciones1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Situaciones1.setText("Otras observaciones");

        txtdelitiva1.setColumns(20);
        txtdelitiva1.setRows(5);
        jScrollPane8.setViewportView(txtdelitiva1);

        Situaciones2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Situaciones2.setText("Resumen multimodal de otras areas implicadas");

        txtdelitiva2.setColumns(20);
        txtdelitiva2.setRows(5);
        jScrollPane9.setViewportView(txtdelitiva2);

        Situaciones3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Situaciones3.setText("Area cognitiva");

        txtdelitiva3.setColumns(20);
        txtdelitiva3.setRows(5);
        jScrollPane10.setViewportView(txtdelitiva3);

        Situaciones4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Situaciones4.setText("Area afectiva");

        txtdelitiva4.setColumns(20);
        txtdelitiva4.setRows(5);
        jScrollPane11.setViewportView(txtdelitiva4);

        Situaciones5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Situaciones5.setText("Area somatica");

        txtdelitiva5.setColumns(20);
        txtdelitiva5.setRows(5);
        jScrollPane12.setViewportView(txtdelitiva5);

        Situaciones6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Situaciones6.setText("Area interpersonal");

        txtdelitiva6.setColumns(20);
        txtdelitiva6.setRows(5);
        jScrollPane13.setViewportView(txtdelitiva6);

        Situaciones7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Situaciones7.setText("Area interpersonal");

        txtdelitiva7.setColumns(20);
        txtdelitiva7.setRows(5);
        jScrollPane14.setViewportView(txtdelitiva7);

        jButton3.setText("MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Firma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Fecha)
                                .addGap(92, 92, 92))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Situaciones6)
                                    .addComponent(Situaciones7)
                                    .addComponent(txtfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtinforme, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Situaciones4)
                                    .addComponent(Situaciones5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(364, 364, 364)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane4)
                                            .addComponent(jScrollPane1)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                                            .addComponent(jTextField1)
                                            .addComponent(jScrollPane8)
                                            .addComponent(jScrollPane10)
                                            .addComponent(jScrollPane9)
                                            .addComponent(jScrollPane2)
                                            .addComponent(jScrollPane6)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Motivo2)
                                                    .addComponent(Motivo1)
                                                    .addComponent(con)
                                                    .addComponent(Situaciones)
                                                    .addComponent(Anam)
                                                    .addComponent(Detalle)
                                                    .addComponent(Motivo)
                                                    .addComponent(Situaciones1)
                                                    .addComponent(Situaciones2)
                                                    .addComponent(Situaciones3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                .addComponent(jScrollPane12)
                                .addComponent(jScrollPane13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Motivo1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Motivo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Motivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Detalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Anam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Situaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Situaciones1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Situaciones2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Situaciones3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Situaciones4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Situaciones5)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(Situaciones6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Situaciones7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(con)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Firma)
                            .addComponent(Fecha))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtinforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
home frame2 = new home();
frame2.setVisible(true);
this.setVisible(false);        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newhistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newhistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newhistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newhistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newhistorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anam;
    private javax.swing.JLabel Detalle;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Firma;
    private javax.swing.JLabel Motivo;
    private javax.swing.JLabel Motivo1;
    private javax.swing.JLabel Motivo2;
    private javax.swing.JLabel Situaciones;
    private javax.swing.JLabel Situaciones1;
    private javax.swing.JLabel Situaciones2;
    private javax.swing.JLabel Situaciones3;
    private javax.swing.JLabel Situaciones4;
    private javax.swing.JLabel Situaciones5;
    private javax.swing.JLabel Situaciones6;
    private javax.swing.JLabel Situaciones7;
    private javax.swing.JLabel con;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextArea txtcon;
    private javax.swing.JTextArea txtconsulta;
    private javax.swing.JTextArea txtconsulta1;
    private javax.swing.JTextArea txtconsulta2;
    private javax.swing.JTextArea txtdelitiva;
    private javax.swing.JTextArea txtdelitiva1;
    private javax.swing.JTextArea txtdelitiva2;
    private javax.swing.JTextArea txtdelitiva3;
    private javax.swing.JTextArea txtdelitiva4;
    private javax.swing.JTextArea txtdelitiva5;
    private javax.swing.JTextArea txtdelitiva6;
    private javax.swing.JTextArea txtdelitiva7;
    private javax.swing.JTextArea txtdelito;
    private javax.swing.JTextField txtfirma;
    private javax.swing.JTextField txtinforme;
    // End of variables declaration//GEN-END:variables
}
